=== Austin795/atc-manager-2/schema/operator.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "id",
    "name",
    "callsign",
    "shortName",
    "color"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "integer",
      "title": "The Id Schema",
      "default": 0,
      "examples": [
        18
      ]
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "examples": [
        "Cathay Pacific"
      ],
      "pattern": "^([\\w ]+)$"
    },
    "callsign": {
      "$id": "#/properties/callsign",
      "type": "string",
      "title": "The Callsign Schema",
      "examples": [
        "CPA"
      ],
      "pattern": "^([A-Z]{3})$"
    },
    "shortName": {
      "$id": "#/properties/shortName",
      "type": "string",
      "title": "The Shortname Schema",
      "examples": [
        "Cathay"
      ],
      "pattern": "^([\\w ]+)$"
    },
    "color": {
      "$id": "#/properties/color",
      "type": "string",
      "title": "The Color Schema",
      "examples": [
        "#006b6e"
      ],
      "pattern": "^(#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?)$"
    }
  }
}

=== Austin795/atc-manager-2/lib/airplane-library/default-operators.json
[
  {
    "id": 0,
    "name": "KLM",
    "shortName": "KLM",
    "callsign": "KLM",
    "color": "#00a1e4"
  },
  {
    "id": 1,
    "name": "Delta Airlines",
    "callsign": "DLT",
    "shortName": "Delta",
    "color": "#003a70"
  },
  {
    "id": 2,
    "name": "JetBlue",
    "callsign": "JBU",
    "shortName": "JetBlue",
    "color": "#003876"
  },
  {
    "id": 3,
    "name": "United Airlines",
    "callsign": "UAL",
    "shortName": "United",
    "color": "#005DAA"
  },
  {
    "id": 4,
    "name": "Southwest Airlines",
    "callsign": "SWA",
    "shortName": "Southwest",
    "color": "#304cb2"
  },
  {
    "id": 5,
    "name": "American Airlines",
    "callsign": "AAL",
    "shortName": "American",
    "color": "#d41525"
  },
  {
    "id": 6,
    "name": "British Airways",
    "callsign": "BAW",
    "shortName": "Speedbird",
    "color": "#2a5c9a"
  },
  {
    "id": 7,
    "name": "Continental Airlines",
    "callsign": "COA",
    "shortName": "Continental",
    "color": "#0060aa"
  },
  {
    "id": 8,
    "name": "Lufthansa",
    "callsign": "DLH",
    "shortName": "Lufthansa",
    "color": "#00225e"
  },
  {
    "id": 9,
    "name": "Air France",
    "callsign": "AFR",
    "shortName": "Air France",
    "color": "#002157"
  },
  {
    "id": 10,
    "name": "China Southern Airlines",
    "callsign": "CSN",
    "shortName": "China Southern",
    "color": "#008dd2"
  },
  {
    "id": 11,
    "name": "China Eastern Airlines",
    "callsign": "CES",
    "shortName": "China Eastern",
    "color": "#e31614"
  },
  {
    "id": 12,
    "name": "All Nippon Airways",
    "callsign": "ANA",
    "shortName": "All Nippon",
    "color": "#083191"
  },
  {
    "id": 13,
    "name": "Ryanair",
    "callsign": "RYR",
    "shortName": "Ryanair",
    "color": "#0027b5"
  },
  {
    "id": 14,
    "name": "Turkish Airlines",
    "callsign": "THY",
    "shortName": "Turkish",
    "color": "#ee2e24"
  },
  {
    "id": 15,
    "name": "Emirates",
    "callsign": "UAE",
    "shortName": "Emirates",
    "color": "#d8131b"
  },
  {
    "id": 16,
    "name": "FedEx Express",
    "callsign": "FDX",
    "shortName": "Fedex",
    "color": "#2a007c"
  },
  {
    "id": 17,
    "name": "UPS Airlines",
    "callsign": "UPS",
    "shortName": "UPS",
    "color": "#fab903"
  },
  {
    "id": 18,
    "name": "Cathay Pacific",
    "callsign": "CPA",
    "shortName": "Cathay",
    "color": "#006b6e"
  },
  {
    "id": 19,
    "name": "Qatar Airways",
    "callsign": "QTR",
    "shortName": "Qatari",
    "color": "#5c0632"
  },
  {
    "id": 20,
    "name": "Korean Air",
    "callsign": "KAL",
    "shortName": "Korean Air",
    "color": "#154d9e"
  },
  {
    "id": 21,
    "name": "Cargolux",
    "callsign": "CLX",
    "shortName": "Cargolux",
    "color": "#d40000"
  },
  {
    "id": 22,
    "name": "Air China",
    "callsign": "CCA",
    "shortName": "Air China",
    "color": "#ee151f"
  },
  {
    "id": 23,
    "name": "Egyptair",
    "callsign": "MSR",
    "shortName": "Egyptair",
    "color": "#00265d"
  },
  {
    "id": 24,
    "name": "Cathay Dragon",
    "callsign": "HDA",
    "shortName": "Dragon",
    "color": "#950714"
  },
  {
    "id": 25,
    "name": "Norwegian Air Shuttle",
    "callsign": "NAX",
    "shortName": "Norwegian",
    "color": "#ff2121"
  },
  {
    "id": 26,
    "name": "Finnair",
    "callsign": "FIN",
    "shortName": "Finnair",
    "color": "#121c83"
  }
]
